### ISSUE TITLE
issue : X has 478 features, but RandomForestClassifier is expecting 4550 features as input.

### ISSUE THREAD

**Issue by subham73** [rani-sneha/DataScience#1]
### preprocess_testing.ipynb
```
def preprocess_text(df):
   df=removing_username(df)
   df=tolowercase(df)
   df['reviews']= df['reviews'].apply(remove_urls)
   df['reviews']=df['reviews'].apply(remove_punctuation)
   sw_list=stopwords.words('english')
   df['reviews'] = df['reviews'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
   df_test=cv.fit_transform(df['reviews']).toarray()
   return df_test
```
fit _Transform() — is convenient and efficient for modelling and transforming the **training** data.
 As this dataset is used for testing. it isn't required I guess and it throws this input mismatch error.

**Comment by subham73** [comment]
try using transform() only 
```
def preprocess_text(df):
   df=removing_username(df)
   df=tolowercase(df)
   df['reviews']= df['reviews'].apply(remove_urls)
   df['reviews']=df['reviews'].apply(remove_punctuation)
   sw_list=stopwords.words('english')
   df['reviews'] = df['reviews'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
   df_test=cv.transform(df['reviews']).toarray()
   return df_test
```
this would work I guess

**Comment by rani-sneha** [comment]
I have tried transform only as well and then it gives other issue like vocabulary not fit and inorder to correct that i had to write fit_transform @subham73

**Comment by rani-sneha** [comment]
I have tried transform only as well and then it gives other issue like vocabulary not fit and inorder to correct that i had to write fit_transform @subham73

**Comment by subham73** [comment]
@rani-sneha can u share the "Top_C.csv" file .

**Comment by rani-sneha** [comment]
This is the file
[Top_C.csv](https://github.com/rani-sneha/DataScience/files/12565363/Top_C.csv)
@subham73 
I have also added the file to the gitHub repo incase this does not work
The problem is that somehow I am unable to preprocess the training data becausse it is already clean and i don't have access to unclean labelled data.

**Comment by subham73** [comment]
@rani-sneha I am not sure what you mean by 
> not having access to unclean labelled data  

but the problem it seems is the bag of words not being saved for the testing_data. 

When CountVectorizer is created from training data, it should be made available for validation and test data. so that we can transform them according to training data. 

In file _model.ipynb_
`X_train_bow = cv.fit_transform(X_train['reviews'].values.astype('U')).toarray()`
we can save this cv
```
X_train_bow = cv.fit_transform(X_train['reviews'].values.astype('U')).toarray()

import joblib
joblib.dump(cv, "vectorizer.pkl")
```
and then load it back in _preprocessor_testing.ipynb_ to transform our test_df
```
import joblib
cv = joblib.load("location of vectorizer.pkl")
test_df = cv.transform(preProcessed_test_df[0]).toarray()
```
i hope rest will run as expected.

**Comment by subham73** [comment]
> This is the file [Top_C.csv](https://github.com/rani-sneha/DataScience/files/12565363/Top_C.csv) @subham73 I have also added the file to the gitHub repo incase this does not work The problem is that somehow I am unable to preprocess the training data becausse it is already clean and i don't have access to unclean labelled data.

ohh I do get it now, when u are manipulating any dataFrame , do store it as a different column in the same dataFrame, or create a dummy of the original dataFrame and apply changes there.

**Comment by subham73** [comment]
@rani-sneha  check the ipynb files under _sentiment-analysis/subh73_ , see if the same issue is happening or not. do use my Twitter_data as prev data was not present.

**Comment by rani-sneha** [comment]
> @rani-sneha I am not sure what you mean by
> 
> > not having access to unclean labelled data
> 
> but the problem it seems is the bag of words not being saved for the testing_data.
> 
> When CountVectorizer is created from training data, it should be made available for validation and test data. so that we can transform them according to training data.
> 
> In file _model.ipynb_ `X_train_bow = cv.fit_transform(X_train['reviews'].values.astype('U')).toarray()` we can save this cv
> 
> ```
> X_train_bow = cv.fit_transform(X_train['reviews'].values.astype('U')).toarray()
> 
> import joblib
> joblib.dump(cv, "vectorizer.pkl")
> ```
> 
> and then load it back in _preprocessor_testing.ipynb_ to transform our test_df
> 
> ```
> import joblib
> cv = joblib.load("location of vectorizer.pkl")
> test_df = cv.transform(preProcessed_test_df[0]).toarray()
> ```
> 
> i hope rest will run as expected.

Yeah, I had to make some changes but yeah it worked . Thanks

**Comment by rani-sneha** [comment]
Issue 1 successfully solved @subham73
